### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by zicklag** [shyiko/vue-document#2]
In order for me to legally use this project's code it needs to have a license specified. Could you please choose an Open Source license for this project?

**Comment by shyiko** [comment]
License is specified at the end of the readme. Anyway, I added [LICENSE (MIT)](https://github.com/shyiko/vue-document/blob/master/LICENSE) file to the repo to make it (more) explicit. :cake:

**Comment by zicklag** [comment]
Oops, I missed it. Thanks! :smile:

**Comment by shyiko** [comment]
@zicklag no worries!
